version: '3'
networks:
  default:
    external: 
      name: app
services:
  zookeeper:
    image: ${DOCKER_REPO}zookeeper:${ZOOKEEPER_DOCKER_TAG}
    container_name: zookeeper
    ports:
      - ${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}
  kafka:
    image: ${DOCKER_REPO}kafka:${KAFKA_DOCKER_TAG}
    container_name: kafka
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=${KAFKA_PORT}
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_CLIENT_PORT}
    depends_on: 
      - zookeeper