# logLevel: DEBUG,INFO
logLevel: DEBUG
# logAllModules: true
gunicorn:
  # worker_per_core will be ignored when workers is set
  worker_per_core: 1
  # max_workers will be ignored when workers is set
  max_workers: 8
  # workers: 4
  log:
    access: "-"
    error: "-"
  grateful_timeout: 120
  timeout: 120
  keepalive: 5
bind: 0.0.0.0:8001
redis:
  host: redis
  port: 6379